### ISSUE TITLE
Tracking issue for 0.1 release

### ISSUE THREAD

**Issue by boguslavsky** [exonum/exonum-client#14]
@boguslavsky:

- [x] Bug fixes and style improvements. PR: #12 
- [x] Rework modules export. Task: #5, PR: #13 
- [x] Update format. Task: #20, PR: #24 
- [x] Fix Jshint. Task: #15 
- [x] Rework error handling: change console.error to throwing errors. Task: #16, PR: #28
- [x] Documentation refactoring. Task: #1, PR: #32
- [x] Publish as npm package. Task: #18 
- [ ] Publish as bower package. Task: #19 
- [ ] Coveralls code coverage + badge. Task: #22

**Comment by boguslavsky** [comment]
Close task withoug publishing to bower #19 and adding of coveralls #22.
